### ISSUE TITLE
Altme Wallet

### ISSUE THREAD

**Issue by jdsika** [GAIA-X4PLC-AAD/gx-credentials#9]
Does the wallet allow to hold multiple private keys e.g. for an admin to be the holder of the company credential on his mobile application as well. Can it be operated in combination with hardware wallets like ledger?

**Comment by flhps** [comment]
Yes, you can load in an arbitrary amount of private keys. For testing, I had 3 different keys in my Altme wallet. I am not aware of support for hardware wallets.

**Comment by jdsika** [comment]
Apparently there is something new now [released today](https://altme.io/blog/add-a-decentralized-identity-DID-to-your-favorite-tezos-wallet/)

**Comment by jdsika** [comment]
Btw this [https://talao.co/altme-identity](https://talao.co/altme-identity) is not working for me. I connect my temple Firefox Broser extension, sign the message, scan the QR code and I see the account ownership card. If I click "add card" it is not displayed in my altme wallet

**Comment by ThierryThevenet** [comment]
At the moment the wallet supports only one did:key + one did:ebsi + one polygonid identity key.. They are derived from the pass phrase.
The other private key are for cryptos , and one can create as many as you one wants
We have not had the use case for several identity key.

**Comment by ThierryThevenet** [comment]
the altme-identity issue is fixed
